### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by erlenbol** [simennj/itsdownloading#10]
Heisann.
Får ut dette i terminal på mac etter å ha valgt hist og logget inn med brukernavn og passord.
Samme brukernavn og passord fungerer fint på web-sidene til itslearning.
Noen idé på hva som ikke fungerer?

Traceback (most recent call last):
  File "itsdownloading.py", line 314, in <module>
    main()
  File "itsdownloading.py", line 31, in main
    console_login()
  File "itsdownloading.py", line 76, in console_login
    logged_in = attempt_login(username, password)
  File "itsdownloading.py", line 88, in attempt_login
    logged_in = confirm_login(confirm_login_page)
  File "itsdownloading.py", line 112, in confirm_login
    hist_extra_login(confirm_login_page)
  File "itsdownloading.py", line 123, in hist_extra_login
    '__VIEWSTATE': tree.xpath('//input[@name="__VIEWSTATE"]/@value')[0],
IndexError: list index out of range

**Comment by simennj** [comment]
Hvilken versjon kjører du? Får du samme feilmelding hvis du skriver inn feil brukernavn og passord?
Jeg har ikke sett det problemet tidligere og jeg klarer ikke å reprodusere det med nyeste versjon og uten Hist konto, men det ser ut som den havner på en uventet side i løpet av påloggingsprosessen.

**Comment by erlenbol** [comment]
Hei, og takk for svar.
Har python 3.6.1 og bruker kommandoen "python3.6 itsdownloading.py".
Testa å skrive inn feil passord, og då kom det beskjed om at passordet var feil.

**Comment by simennj** [comment]
Ok, jeg skal se nærmere på det når jeg får tid i helgen da.

**Comment by simennj** [comment]
Kunne du testet nyeste versjon og sendt meg login_error.html filen som lagres?

**Comment by erlenbol** [comment]
Hei
Har skjedd noko med kontoen min i.l.a. helga. No får eg "wrong username or password" i innlogging. Kjem inn på hist.itslearning.com som vanlig, men kjem ikkje inn på webmail, innsida lenger. Kan gjera eit forsøk igjen i morgon tidlig.

**Comment by simennj** [comment]
Viste seg å være at påloggingen feilet hvis man ikke hadde satt feide til å alltid dele data med itslearning på forhånd. Har dessverre ikke tid til å ordne det i scriptet før ting blir stengt ned om 3 dager, så hvis noen andre får dette problemet så prøv å logge på gjennom linken på innsida (https://innsida.ntnu.no/lms-hist) og huk av "Godta også for fremtiden" før du trykker fortsett. Da skal scriptet fungere.

**Comment by OpusMagnus** [comment]
Jeg får også "wrong username of password", og får ikke opp noe "Godta også for fremtiden".
Er det noe å hake av i settings ellernoe? Innlogging fungerer fremdeles selv om deadline er overløpt (for now)

**Comment by simennj** [comment]
Det dukker altså ikke opp på https://innsida.ntnu.no/lms-hist heller?

**Comment by OpusMagnus** [comment]
Nei desverre. På nettleser med cookies kommer jeg rett inn til innlogging uten noen valg utenom å logge inn, og på incognito kommer jeg til innlogging som ikke inneholder HiST https://www.dropbox.com/s/6ux4tf16frd4gzt/Screen%20Shot%202017-07-16%20at%2020.38.44.png?dl=0

**Comment by simennj** [comment]
Prøv med NTNU istedenfor, mener å huske at det fungerte.

**Comment by OpusMagnus** [comment]
Desverre fungerer ikke det, men det går bra. Har fått ut det jeg trenger fra ntnu kontoen (master), og det fra hist (bachelor) var mer for nostalgi.
